### ISSUE TITLE
rendercomplete event

### ISSUE THREAD

**Issue by nobodo** [lolochristen/OpenLayers.Blazor#11]
Hi, the rendercomplete event would be useful to be exposed.

I'm looking for a way to make sure that map is finished loading and rendering, and I was thinking that the 'rendercomplete' event might be the solution.

**Comment by nobodo** [comment]
#12 created, feel free to comment and suggest improvements, I'm not sure if everything is done by the book but at least I got it to do what I wanted

**Comment by lolochristen** [comment]
Implemented via #13, available in Release 1.2.0
