### ISSUE TITLE
Polygons on swisstopo cadastrel web map

### ISSUE THREAD

**Issue by DrMueller** [lolochristen/OpenLayers.Blazor#15]
Hello there

First of all, awesome repository, thank you very much! I'm quite new to the topic and your repository offers a great starting point. Probably you could give me a hint: I'm trying to reproduce the feature here https://map.geo.admin.ch/index.html?zoom=10&lang=de&topic=swisstopo&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.kantone.cadastralwebmap-farbe&catalogNodes=1396,1482,1397,1411,1424,1427&E=2693182.85&N=1139348.58. Clicking on a entry highlights it and shows some information.

This has to be a feature of the respective map (cadastrel), as only it knows the exact data. But I guess I would need to access the data and draw myself. Could you give me a hint, if I'm on the right path here?

Again, thank you very much.

With best regards

Matthias

**Comment by lolochristen** [comment]
I looked into the map.geo.amin.ch implementation. They built that custom by calling the following API on map click. 

https://api3.geo.admin.ch/rest/services/all/MapServer/identify?geometry=2693487,1138873.5&geometryFormat=geojson&geometryType=esriGeometryPoint&imageDisplay=1408,1145,96&lang=de&layers=all:ch.kantone.cadastralwebmap-farbe&limit=10&mapExtent=2692836.9170767884,1138278.2143541584,2694244.9170767884,1139423.2143541584&returnGeometry=true&sr=2056&tolerance=10

I have added recently capabilities to draw custom shapes into OpenLayers.Blazor. You could implement the same behavior with this. 
And by the way, geo.admin.ch does not return the layer with by calling WMS capabilities endpoint. The WMTS endpoint does return it. But finally, geo.admin.ch , use the WMS endpoint to get the tiles. So just add a WMS tile with the layer id ch.kantone.cadastralwebmap-farbe.

**Comment by DrMueller** [comment]
> I looked into the map.geo.amin.ch implementation. They built that custom by calling the following API on map click.
> 
> https://api3.geo.admin.ch/rest/services/all/MapServer/identify?geometry=2693487,1138873.5&geometryFormat=geojson&geometryType=esriGeometryPoint&imageDisplay=1408,1145,96&lang=de&layers=all:ch.kantone.cadastralwebmap-farbe&limit=10&mapExtent=2692836.9170767884,1138278.2143541584,2694244.9170767884,1139423.2143541584&returnGeometry=true&sr=2056&tolerance=10
> 
> I have added recently capabilities to draw custom shapes into OpenLayers.Blazor. You could implement the same behavior with this. And by the way, geo.admin.ch does not return the layer with by calling WMS capabilities endpoint. The WMTS endpoint does return it. But finally, geo.admin.ch , use the WMS endpoint to get the tiles. So just add a WMS tile with the layer id ch.kantone.cadastralwebmap-farbe.

Hi Laurent, thank you very much. Looking into your changes.

**Comment by lolochristen** [comment]
Hi Dr. fyi, I have extended the layer demo page with call to API's geo.admin.ch to get a geojson with area and load it. Also when clicking on it it shows its properties. Actually the same that swisstop does. To make that work, I had to fix some coordinates handling and needed to pass the projection to the geojson loading method.

**Comment by DrMueller** [comment]
@lolochristen Sorry for the late response, thank you very much. Looking into it, this will help us a great deal.
