### ISSUE TITLE
Limiting the map to a certain region

### ISSUE THREAD

**Issue by OskarZyg** [lolochristen/OpenLayers.Blazor#34]
Looking at the [Swiss Map](https://openlayers-blazor-demo.laurent-christen.ch/swissmaplayersdemo), I am not able to leave its bounds after zooming out.

Is there a way to define this behaviour on the OpenStreetMap?

I can't seem to find how to define this. Apologies if this is already a feature that I couldn't find.

**Comment by lolochristen** [comment]
OpenStreetMap component is just a wrapper of this:
``` .razor
<Map>
 <Layers>
         <Layer SourceType="SourceType.OMS"  Extent="@(new double[] { -180, -90, 180, 90})" />
 </Layers>
</Map>
```

In this structure, you can define the Extent attribute for the map.

**Comment by OskarZyg** [comment]
Using the above code (with OMS corrected to OSM), results in this. Different values (copy pasting extent from the OSM demo page) seem to lock me into the same place.
<img width="1186" alt="image" src="https://github.com/lolochristen/OpenLayers.Blazor/assets/56176746/b93daaf9-f419-4581-a61d-317dfc7d2240">

Is there something I am missing?

**Comment by OskarZyg** [comment]
( @lolochristen , apologies for the ping but i am not sure if GitHub notifies participants after the issue was closed, apologies if I'm double-pinging!!)

**Comment by lolochristen** [comment]
There is an issue with handling the extent in the right projection. It could be a bigger problem because OSM presentation is in EPSG:3857 but coordinates are set/returned in EPSG:4326. I'll have a look when time allows me....
