### ISSUE TITLE
C# and Javascript Error  : OnInternalCenterChanged(Coordinate coordinate)

### ISSUE THREAD

**Issue by VibertJ** [lolochristen/OpenLayers.Blazor#37]
Hello, 
I have the following Javascript Error in my projet and I can see you have the exact same problem on your demo site : [https://openlayers-blazor-demo.laurent-christen.ch/](https://openlayers-blazor-demo.laurent-christen.ch/)
`blazor.webassembly.js:1  Uncaught (in promise) Error: System.NullReferenceException: Arg_NullReferenceException
   at OpenLayers.Blazor.Map.OnInternalCenterChanged(/Coordinate coordinate)
    at g.endInvokeDotNetFromJS (blazor.webassembly.js:1:3136)
    at Object.gn [as endInvokeDotNetFromJS] (blazor.webassembly.js:1:58655)
    ...`
Those errors accumulates (see my screenshot of DevTools) and seems to have secondaries effects on you demo project. 
(I'm not sure but markers don't work anymore)
Any ideas of a fix ? 
Best regards,
Jerome
<img width="589" alt="image" src="https://github.com/lolochristen/OpenLayers.Blazor/assets/1779350/1fa6ba4d-ba03-41a4-83a4-02677bbf4c27">
In my Blazor server project, the debugger stops on OnInternalCenterChange (screenshot bellow)
![image](https://github.com/lolochristen/OpenLayers.Blazor/assets/1779350/e85a05d0-d85c-4370-be64-5c8e47d97082)

**Comment by artemfomin** [comment]
Same issue with OSM. No fix yet

**Comment by artemfomin** [comment]
As it is the first error thrown by JS might appear (yet untraceable) that other features like adding a marker don't work due to initial map JS object failure. Tried different ways of dynamic adding markers (from the one from examples to manual `SetLayers()`) but none works.

**Comment by lolochristen** [comment]
The component had a major serialization issue with some local settings/globalization settings. When explicitly enforcing locals with a comma as decimal separators, I could also not add markers as coordinates have been invalid. The serialization issue is fixed (including some unit tests) in latest version 1.5.4. Please verify.

**Comment by VibertJ** [comment]
For my specific context (<OpenStreetMap>), you have fixed the Javascript error and made the add of Markers functional. 
I appreciate your effort ! 🙏🏼 
Jerome
