### ISSUE TITLE
Coordinates don't have decimal points

### ISSUE THREAD

**Issue by BluMasc** [lolochristen/OpenLayers.Blazor#38]
I am using an OpenStreetMap object with the OnClick event attached. In my function i have Coordinate c as a parameter. But the Lat and Lon values in this coordinate are missing their decimal Point. 

8474733390625042 instead of 8.474733390625042

I can't use context to discern if a number has 1 or 2 places before the decimal point. 

My best guess is that this has something to do with CultureInfo, but i am not sure.

**Comment by lolochristen** [comment]
I can confirm. Parsing coordinates between js interop and dotnet makes issues when decimal point is a comma while JS still uses a point. Fix will be soon ready. (Or move to a country where the decimal point is fixed)

**Comment by lolochristen** [comment]
I assume it can be closed with #41
