### ISSUE TITLE
Polygon in Features Tag

### ISSUE THREAD

**Issue by BruderJohn** [lolochristen/OpenLayers.Blazor#39]
I want to add a Polygon inside the Features Tag. Is this possible?

**Comment by lolochristen** [comment]
Do you mean adding just adding a polygon as shape/feautre. It is supported via code but not yet as razor component (child of Features). I'll add this to my backlog....

**Comment by lolochristen** [comment]
Actually, it should work by adding a <Shape ShapeType="ShapeType.Polygon" ..... />

**Comment by lolochristen** [comment]
I have added Polygon support. It's currently on the main branch. I will release it asap.

**Comment by BruderJohn** [comment]
Ok👍. 
Is there any Example on how to add polygons via code?
