### ISSUE TITLE
Subfolder deployment

### ISSUE THREAD

**Issue by nicowitteman** [lolochristen/OpenLayers.Blazor#4]
In https://github.com/lolochristen/OpenLayers.Blazor/blob/39dfcbe8f0231289581dec7158a0638a9a1e9cb7/src/OpenLayers.Blazor/Map.razor.cs#L218, can you ad a "." (period) to the path, to make it read '...$"./_content/...' please? Otherwise it does not run correctly when deployed to a folder.

**Comment by lolochristen** [comment]
fixed. Thanks for the input. 
do you need a new release or can you wait?

**Comment by nicowitteman** [comment]
Thank you. I can wait. Regards,NicoOp 30 mei 2023 om 08:01 heeft Laurent Christen ***@***.***> het volgende geschreven:﻿
fixed. Thanks for the input.
do you need a new release or can you wait?
