### ISSUE TITLE
Coordinate constructor Lat/Lon

### ISSUE THREAD

**Issue by blazorber** [lolochristen/OpenLayers.Blazor#40]
Hey there,

new to your repo and testing your demo right now.

Can you explain me, why i have to set Lat and Lon at the Coordinate-constructor like this to get Frankfurt on the map:

Demo:
![image](https://github.com/lolochristen/OpenLayers.Blazor/assets/128692095/41b59e62-44e3-4e01-a005-626720cb2a27)
![image](https://github.com/lolochristen/OpenLayers.Blazor/assets/128692095/4c92e217-9b66-4dce-a2fd-8e378d648e88)

G-Maps:
![image](https://github.com/lolochristen/OpenLayers.Blazor/assets/128692095/b8f9be45-d1ef-4668-9864-da670ed5d0f6)

![image](https://github.com/lolochristen/OpenLayers.Blazor/assets/128692095/35ae620b-3f23-4cf8-88f7-b366b1b0a8d7)

If i dont get it wrong then the Coordinate-constructor binding the parameters to the wrong attributes:

![image](https://github.com/lolochristen/OpenLayers.Blazor/assets/128692095/9c57292a-17a7-4741-bf67-4ebf73f237c8)

I saw your Major Changes note at your readme, but im still a bit confused. Maybe you can help me back on track. Thanks in advance.

Best regards

**Comment by lolochristen** [comment]
You are right. X = Longitude, Y = Latitude.

**Comment by lolochristen** [comment]
It's fixed in latest 1.5.4. Please check.

**Comment by blazorber** [comment]
Thank you very much! Unfortunately im still working with .Net 6. I can only use version 1.5.0, but I will update to .Net 8 in the future and after that im able to test your new version.

Take care!

Best regards

**Comment by blazorber** [comment]
That would be appreciated, if you got time to support .net 6 again! I could upgrade to your latest version and it would be awesome for other .net 6 users too.
