### ISSUE TITLE
Feature Request - .Net 6 Support

### ISSUE THREAD

**Issue by blazorber** [lolochristen/OpenLayers.Blazor#46]
Good morning,

as you mentioned in #40. It would be appreciated to get .Net 6 support back, if you got time for this.

Thanks in advance.

Best regards

**Comment by lolochristen** [comment]
Version 1.5.5 has already net6.0 support.

**Comment by blazorber** [comment]
Oh sorry, i missed that in the "Whats changed" of the 1.5.5 version. I saw it in the full changelog now. Thank you very much!
