### ISSUE TITLE
Feature - Set Interaction on map

### ISSUE THREAD

**Issue by msdevcode** [lolochristen/OpenLayers.Blazor#48]
Good morning,

is it possible to set the interaction of the map on mobile devices e.g. with two fingers or on desktop with ctrl + mouse or keyboard arrows?

It would be great to not change the map when the user is scrolling the view.

If the feature is alreay there, maybe you can add an example to the readme.

Thank you in advance.

Best regards

**Comment by OskarZyg** [comment]
related: mobile users are able to rotate the map. in my experience, they usually do this unintentionally and get confused. would love if i had an option to restrict / disable this

**Comment by lolochristen** [comment]
Controlling the interactions is not yet possible. I made a proposal in PR #49. With the change, shift + mouse will do the same as two fingers. Also, all interactions can be disabled now.
I will release it after some tests/feedback.
Hope this helps. l

**Comment by msdevcode** [comment]
Disable all interactions is workin fine. Thanks alot and keep up the good work!
