### ISSUE TITLE
Issues with Mapcontrols

### ISSUE THREAD

**Issue by blazorber** [lolochristen/OpenLayers.Blazor#56]
Good morning,

i added the new Mapcontrols e.g. Fullscreen or Rotate onto the map. Now i disable all the interactions of the map via a button. The new Mapcontrols are still useable.

Is it possible to align the Mapcontrols among each other? When i use Fullscreen-Mode and rotate the map the Rotate-Button hides the Fullscreen-Button.

I used the Openstreetmap-Control.

Thank you in advance.

Best regards

**Comment by lolochristen** [comment]
The controls are fully managed/rendered by the underlying OpenLayers library. I have noticed as well the same behaviour but have not found a way to change it. Check out their repo/issues for a solution. If you have found a way, I'll support you to integrate it.

**Comment by blazorber** [comment]
I found a way to display the controls lower than the fullscreen-control:

https://openlayers.org/en/latest/examples/full-screen-drag-rotate-and-zoom.html#:~:text=Hold%20down%20Shift%2BDrag%20to,corner%20to%20go%20full%20screen.

`/* position the rotate control lower than usual */
      .map .ol-rotate {
        top: 3em;
      }`

It works for me when i use

`.ol-rotate {
        top: 5em;
      }`

at my view.

But i still couldnt figure out to disable the controls when all interactions are disabled for the map.

**Comment by lolochristen** [comment]
The layout is defined by openlayers library. The approach via CSS might work. The latest 2.0.0 release will disable any interaction now.

**Comment by blazorber** [comment]
Disable interactions works with 2.0.1. Thank you very much and keep up the good work/support! 🥇

Best regards
