### ISSUE TITLE
Publish demo errors

### ISSUE THREAD

**Issue by nicowitteman** [lolochristen/OpenLayers.Blazor#6]
Hi,
I cannot get the publishing of the Demo project working, it appears it has to do with python versions, but I can't figure it out. The Demo.Server publishes fine, and both projects run OK on my dev machine. I am using VS2022, v17.6.2, with workload wasm-tools installed. Any ideas? 

Before failing, it gives me this warning:
`C:\Program Files\dotnet\packs\Microsoft.NET.Runtime.WebAssembly.Sdk\7.0.5\Sdk\WasmApp.Native.targets(502,5): Warning : Emscripten version mismatch. The runtime pack in C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Runtime.Mono.browser-wasm\7.0.5 expects 'emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.12 (38d1292ba2f5b4a7c8518931f5ae6f97ef0f6827)', but emcc being used has version ''. This might cause build failures.
`
Regards, 
Nico

**Comment by lolochristen** [comment]
Hi! Sorry, I have never faced this error. I have compiled the solution on multiple machine without such error. Can you build any other Blazor Wasm solution?

**Comment by nicowitteman** [comment]
More recent info here: https://github.com/dotnet/AspNetCore.Docs/issues/29422. It is not a showstopper, never you mind.
